import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for Physical AI & Humanoid Robotics book
  roboticsSidebar: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics',
      collapsible: true,
      collapsed: false,
      items: [
        'intro', // Introduction file at the top level under the main category
        // ------------------------------
        // MODULE 1 - The Robotic Nervous System (ROS 2)
        // ------------------------------
        {
          type: 'category',
          label: 'Module 1 - The Robotic Nervous System (ROS 2)',
          collapsible: true,
          collapsed: false,
          items: [
            'modules/module1/chapter1',
            'modules/module1/chapter2',
            'modules/module1/chapter3',
            'modules/module1/chapter4',
            'modules/module1/chapter5',
            'modules/module1/chapter6'
          ]
        },

        // ------------------------------
        // MODULE 2 - The Digital Twin (Gazebo & Unity)
        // ------------------------------
        {
          type: 'category',
          label: 'Module 2 - The Digital Twin (Gazebo & Unity)',
          collapsible: true,
          collapsed: false,
          items: [
            'modules/module2/chapter1',
            'modules/module2/chapter2',
            'modules/module2/chapter3',
            'modules/module2/chapter4',
            'modules/module2/chapter5',
            'modules/module2/chapter6'
          ]
        },

        // ------------------------------
        // MODULE 3 - The AI-Robot Brain (NVIDIA Isaac™)
        // ------------------------------
        {
          type: 'category',
          label: 'Module 3 - The AI-Robot Brain (NVIDIA Isaac™)',
          collapsible: true,
          collapsed: false,
          items: [
            'modules/module3/chapter1',
            'modules/module3/chapter2',
            'modules/module3/chapter3',
            'modules/module3/chapter4',
            'modules/module3/chapter5',
            'modules/module3/chapter6'
          ]
        },

        // ------------------------------
        // MODULE 4 - Vision-Language-Action (VLA)
        // ------------------------------
        {
          type: 'category',
          label: 'Module 4 - Vision-Language-Action (VLA)',
          collapsible: true,
          collapsed: false,
          items: [
            'modules/module4/chapter1',
            'modules/module4/chapter2',
            'modules/module4/chapter3',
            'modules/module4/chapter4',
            'modules/module4/chapter5',
            'modules/module4/chapter6'
          ]
        }
      ]
    }
  ]
};

export default sidebars;
