import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for Physical AI & Humanoid Robotics book
  roboticsSidebar: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Module 1 - Foundations of Physical AI',
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'Chapter 1: Introduction to Physical AI',
              collapsible: true,
              collapsed: false,
              items: ['modules/module1/chapter1']
            },
            {
              type: 'category',
              label: 'Chapter 2: Robotics Fundamentals',
              collapsible: true,
              collapsed: false,
              items: ['modules/module1/chapter2']
            },
            {
              type: 'category',
              label: 'Chapter 3: Sensor Integration and Perception',
              collapsible: true,
              collapsed: false,
              items: ['modules/module1/chapter3']
            },
            {
              type: 'category',
              label: 'Chapter 4: Actuation and Control',
              collapsible: true,
              collapsed: false,
              items: ['modules/module1/chapter4']
            },
            {
              type: 'category',
              label: 'Chapter 5: Kinematics and Dynamics',
              collapsible: true,
              collapsed: false,
              items: ['modules/module1/chapter5']
            },
            {
              type: 'category',
              label: 'Chapter 6: Introduction to Humanoid Robotics',
              collapsible: true,
              collapsed: false,
              items: ['modules/module1/chapter6']
            }
          ]
        },
        {
          type: 'category',
          label: 'Module 2 - Advanced Robotics and AI Integration',
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'Chapter 7: Machine Learning for Robotics',
              collapsible: true,
              collapsed: false,
              items: ['modules/module2/chapter1']
            },
            {
              type: 'category',
              label: 'Chapter 8: Deep Learning in Robotics',
              collapsible: true,
              collapsed: false,
              items: ['modules/module2/chapter2']
            },
            {
              type: 'category',
              label: 'Chapter 9: Reinforcement Learning for Control',
              collapsible: true,
              collapsed: false,
              items: ['modules/module2/chapter3']
            },
            {
              type: 'category',
              label: 'Chapter 10: Human-Robot Interaction',
              collapsible: true,
              collapsed: false,
              items: ['modules/module2/chapter4']
            },
            {
              type: 'category',
              label: 'Chapter 11: Collaborative Robotics',
              collapsible: true,
              collapsed: false,
              items: ['modules/module2/chapter5']
            },
            {
              type: 'category',
              label: 'Chapter 12: Swarm Robotics and Multi-Agent Systems',
              collapsible: true,
              collapsed: false,
              items: ['modules/module2/chapter6']
            }
          ]
        },
        {
          type: 'category',
          label: 'Module 3 - Humanoid Robotics: Design and Embodiment',
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'Chapter 13: Humanoid Robot Design Principles',
              collapsible: true,
              collapsed: false,
              items: ['modules/module3/chapter1']
            },
            {
              type: 'category',
              label: 'Chapter 14: Actuators and Sensors for Humanoids',
              collapsible: true,
              collapsed: false,
              items: ['modules/module3/chapter2']
            },
            {
              type: 'category',
              label: 'Chapter 15: Humanoid Locomotion and Balance',
              collapsible: true,
              collapsed: false,
              items: ['modules/module3/chapter3']
            },
            {
              type: 'category',
              label: 'Chapter 16: Humanoid Manipulation and Grasping',
              collapsible: true,
              collapsed: false,
              items: ['modules/module3/chapter4']
            },
            {
              type: 'category',
              label: 'Chapter 17: Whole-Body Control for Humanoids',
              collapsible: true,
              collapsed: false,
              items: ['modules/module3/chapter5']
            },
            {
              type: 'category',
              label: 'Chapter 18: Humanoid Robot Programming Frameworks',
              collapsible: true,
              collapsed: false,
              items: ['modules/module3/chapter6']
            }
          ]
        },
        {
          type: 'category',
          label: 'Module 4 - Advanced Humanoid AI and Applications',
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'Chapter 19: Cognitive Architectures for Humanoids',
              collapsible: true,
              collapsed: false,
              items: ['modules/module4/chapter1']
            },
            {
              type: 'category',
              label: 'Chapter 20: Learning from Demonstration and Imitation',
              collapsible: true,
              collapsed: false,
              items: ['modules/module4/chapter2']
            },
            {
              type: 'category',
              label: 'Chapter 21: Social and Ethical AI in Humanoids',
              collapsible: true,
              collapsed: false,
              items: ['modules/module4/chapter3']
            },
            {
              type: 'category',
              label: 'Chapter 22: Advanced Perception for Humanoids',
              collapsible: true,
              collapsed: false,
              items: ['modules/module4/chapter4']
            },
            {
              type: 'category',
              label: 'Chapter 23: Future of Physical AI and Humanoid Robotics',
              collapsible: true,
              collapsed: false,
              items: ['modules/module4/chapter5']
            },
            {
              type: 'category',
              label: 'Chapter 24: Conclusion and Advanced Topics',
              collapsible: true,
              collapsed: false,
              items: ['modules/module4/chapter6']
            }
          ]
        }
      ]
    }
  ]
};

export default sidebars;
